#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SedenaServices.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sedena")]
	public partial class DBSedenaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAgente(Agente instance);
    partial void UpdateAgente(Agente instance);
    partial void DeleteAgente(Agente instance);
    partial void InsertConductor(Conductor instance);
    partial void UpdateConductor(Conductor instance);
    partial void DeleteConductor(Conductor instance);
    partial void InsertFuncion(Funcion instance);
    partial void UpdateFuncion(Funcion instance);
    partial void DeleteFuncion(Funcion instance);
    partial void InsertEncargado(Encargado instance);
    partial void UpdateEncargado(Encargado instance);
    partial void DeleteEncargado(Encargado instance);
    partial void InsertSesion(Sesion instance);
    partial void UpdateSesion(Sesion instance);
    partial void DeleteSesion(Sesion instance);
    partial void InsertTirador(Tirador instance);
    partial void UpdateTirador(Tirador instance);
    partial void DeleteTirador(Tirador instance);
		#endregion
		public DBSedenaDataContext() :
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SedenaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		public DBSedenaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSedenaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSedenaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSedenaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Agente> Agente
		{
			get
			{
				return this.GetTable<Agente>();
			}
		}
		
		public System.Data.Linq.Table<Actualizacion> Actualizacion
		{
			get
			{
				return this.GetTable<Actualizacion>();
			}
		}
		
		public System.Data.Linq.Table<Conductor> Conductor
		{
			get
			{
				return this.GetTable<Conductor>();
			}
		}
		
		public System.Data.Linq.Table<Funcion> Funcion
		{
			get
			{
				return this.GetTable<Funcion>();
			}
		}
		
		public System.Data.Linq.Table<Entorno> Entorno
		{
			get
			{
				return this.GetTable<Entorno>();
			}
		}
		
		public System.Data.Linq.Table<Encargado> Encargado
		{
			get
			{
				return this.GetTable<Encargado>();
			}
		}
		
		public System.Data.Linq.Table<Sesion> Sesion
		{
			get
			{
				return this.GetTable<Sesion>();
			}
		}
		
		public System.Data.Linq.Table<Tirador> Tirador
		{
			get
			{
				return this.GetTable<Tirador>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Agente")]
	public partial class Agente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Agente;
		
		private string _Matricula;
		
		private string _Grado;
		
		private string _Nombre;
		
		private string _Distintivo;
		
		private string _Arma;
		
		private System.Nullable<int> _Existencia;
		
		private EntitySet<Funcion> _Funcion;
		
		private EntitySet<Encargado> _Encargado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_AgenteChanging(int value);
    partial void OnId_AgenteChanged();
    partial void OnMatriculaChanging(string value);
    partial void OnMatriculaChanged();
    partial void OnGradoChanging(string value);
    partial void OnGradoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDistintivoChanging(string value);
    partial void OnDistintivoChanged();
    partial void OnArmaChanging(string value);
    partial void OnArmaChanged();
    partial void OnExistenciaChanging(System.Nullable<int> value);
    partial void OnExistenciaChanged();
    #endregion
		
		public Agente()
		{
			this._Funcion = new EntitySet<Funcion>(new Action<Funcion>(this.attach_Funcion), new Action<Funcion>(this.detach_Funcion));
			this._Encargado = new EntitySet<Encargado>(new Action<Encargado>(this.attach_Encargado), new Action<Encargado>(this.detach_Encargado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Agente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Agente
		{
			get
			{
				return this._Id_Agente;
			}
			set
			{
				if ((this._Id_Agente != value))
				{
					this.OnId_AgenteChanging(value);
					this.SendPropertyChanging();
					this._Id_Agente = value;
					this.SendPropertyChanged("Id_Agente");
					this.OnId_AgenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricula", DbType="VarChar(30)")]
		public string Matricula
		{
			get
			{
				return this._Matricula;
			}
			set
			{
				if ((this._Matricula != value))
				{
					this.OnMatriculaChanging(value);
					this.SendPropertyChanging();
					this._Matricula = value;
					this.SendPropertyChanged("Matricula");
					this.OnMatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grado", DbType="VarChar(30)")]
		public string Grado
		{
			get
			{
				return this._Grado;
			}
			set
			{
				if ((this._Grado != value))
				{
					this.OnGradoChanging(value);
					this.SendPropertyChanging();
					this._Grado = value;
					this.SendPropertyChanged("Grado");
					this.OnGradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distintivo", DbType="VarChar(30)")]
		public string Distintivo
		{
			get
			{
				return this._Distintivo;
			}
			set
			{
				if ((this._Distintivo != value))
				{
					this.OnDistintivoChanging(value);
					this.SendPropertyChanging();
					this._Distintivo = value;
					this.SendPropertyChanged("Distintivo");
					this.OnDistintivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arma", DbType="VarChar(30)")]
		public string Arma
		{
			get
			{
				return this._Arma;
			}
			set
			{
				if ((this._Arma != value))
				{
					this.OnArmaChanging(value);
					this.SendPropertyChanging();
					this._Arma = value;
					this.SendPropertyChanged("Arma");
					this.OnArmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Existencia", DbType="Int")]
		public System.Nullable<int> Existencia
		{
			get
			{
				return this._Existencia;
			}
			set
			{
				if ((this._Existencia != value))
				{
					this.OnExistenciaChanging(value);
					this.SendPropertyChanging();
					this._Existencia = value;
					this.SendPropertyChanged("Existencia");
					this.OnExistenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Agente_Funcion", Storage="_Funcion", ThisKey="Id_Agente", OtherKey="Id_Agente")]
		public EntitySet<Funcion> Funcion
		{
			get
			{
				return this._Funcion;
			}
			set
			{
				this._Funcion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Agente_Encargado", Storage="_Encargado", ThisKey="Id_Agente", OtherKey="Id_Agente")]
		public EntitySet<Encargado> Encargado
		{
			get
			{
				return this._Encargado;
			}
			set
			{
				this._Encargado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Funcion(Funcion entity)
		{
			this.SendPropertyChanging();
			entity.Agente = this;
		}
		
		private void detach_Funcion(Funcion entity)
		{
			this.SendPropertyChanging();
			entity.Agente = null;
		}
		
		private void attach_Encargado(Encargado entity)
		{
			this.SendPropertyChanging();
			entity.Agente = this;
		}
		
		private void detach_Encargado(Encargado entity)
		{
			this.SendPropertyChanging();
			entity.Agente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Actualizacion")]
	public partial class Actualizacion
	{
		
		private string _Ultima_Actualizacion;
		
		private System.Nullable<int> _Numero_Agentes;
		
		private System.Nullable<int> _Numero_Encargados;
		
		public Actualizacion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ultima_Actualizacion", DbType="VarChar(50)")]
		public string Ultima_Actualizacion
		{
			get
			{
				return this._Ultima_Actualizacion;
			}
			set
			{
				if ((this._Ultima_Actualizacion != value))
				{
					this._Ultima_Actualizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Agentes", DbType="Int")]
		public System.Nullable<int> Numero_Agentes
		{
			get
			{
				return this._Numero_Agentes;
			}
			set
			{
				if ((this._Numero_Agentes != value))
				{
					this._Numero_Agentes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Encargados", DbType="Int")]
		public System.Nullable<int> Numero_Encargados
		{
			get
			{
				return this._Numero_Encargados;
			}
			set
			{
				if ((this._Numero_Encargados != value))
				{
					this._Numero_Encargados = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Conductor")]
	public partial class Conductor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Funcion;
		
		private System.Nullable<int> _Colisiones;
		
		private System.Nullable<double> _Tiempo;
		
		private System.Nullable<bool> _Mision_Cumplida;
		
		private System.Nullable<bool> _Uso_Correcto;
		
		private EntityRef<Funcion> _Funcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_FuncionChanging(int value);
    partial void OnId_FuncionChanged();
    partial void OnColisionesChanging(System.Nullable<int> value);
    partial void OnColisionesChanged();
    partial void OnTiempoChanging(System.Nullable<double> value);
    partial void OnTiempoChanged();
    partial void OnMision_CumplidaChanging(System.Nullable<bool> value);
    partial void OnMision_CumplidaChanged();
    partial void OnUso_CorrectoChanging(System.Nullable<bool> value);
    partial void OnUso_CorrectoChanged();
    #endregion
		
		public Conductor()
		{
			this._Funcion = default(EntityRef<Funcion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Funcion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Funcion
		{
			get
			{
				return this._Id_Funcion;
			}
			set
			{
				if ((this._Id_Funcion != value))
				{
					if (this._Funcion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_FuncionChanging(value);
					this.SendPropertyChanging();
					this._Id_Funcion = value;
					this.SendPropertyChanged("Id_Funcion");
					this.OnId_FuncionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colisiones", DbType="Int")]
		public System.Nullable<int> Colisiones
		{
			get
			{
				return this._Colisiones;
			}
			set
			{
				if ((this._Colisiones != value))
				{
					this.OnColisionesChanging(value);
					this.SendPropertyChanging();
					this._Colisiones = value;
					this.SendPropertyChanged("Colisiones");
					this.OnColisionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tiempo", DbType="Float")]
		public System.Nullable<double> Tiempo
		{
			get
			{
				return this._Tiempo;
			}
			set
			{
				if ((this._Tiempo != value))
				{
					this.OnTiempoChanging(value);
					this.SendPropertyChanging();
					this._Tiempo = value;
					this.SendPropertyChanged("Tiempo");
					this.OnTiempoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mision_Cumplida", DbType="Bit")]
		public System.Nullable<bool> Mision_Cumplida
		{
			get
			{
				return this._Mision_Cumplida;
			}
			set
			{
				if ((this._Mision_Cumplida != value))
				{
					this.OnMision_CumplidaChanging(value);
					this.SendPropertyChanging();
					this._Mision_Cumplida = value;
					this.SendPropertyChanged("Mision_Cumplida");
					this.OnMision_CumplidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uso_Correcto", DbType="Bit")]
		public System.Nullable<bool> Uso_Correcto
		{
			get
			{
				return this._Uso_Correcto;
			}
			set
			{
				if ((this._Uso_Correcto != value))
				{
					this.OnUso_CorrectoChanging(value);
					this.SendPropertyChanging();
					this._Uso_Correcto = value;
					this.SendPropertyChanged("Uso_Correcto");
					this.OnUso_CorrectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Funcion_Conductor", Storage="_Funcion", ThisKey="Id_Funcion", OtherKey="Id_Funcion", IsForeignKey=true)]
		public Funcion Funcion
		{
			get
			{
				return this._Funcion.Entity;
			}
			set
			{
				Funcion previousValue = this._Funcion.Entity;
				if (((previousValue != value) 
							|| (this._Funcion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Funcion.Entity = null;
						previousValue.Conductor = null;
					}
					this._Funcion.Entity = value;
					if ((value != null))
					{
						value.Conductor = this;
						this._Id_Funcion = value.Id_Funcion;
					}
					else
					{
						this._Id_Funcion = default(int);
					}
					this.SendPropertyChanged("Funcion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Funcion")]
	public partial class Funcion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Funcion;
		
		private System.Nullable<int> _Id_Agente;
		
		private System.Nullable<int> _Id_Sesion;
		
		private string _Funcion1;
		
		private EntityRef<Conductor> _Conductor;
		
		private EntityRef<Tirador> _Tirador;
		
		private EntityRef<Agente> _Agente;
		
		private EntityRef<Sesion> _Sesion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_FuncionChanging(int value);
    partial void OnId_FuncionChanged();
    partial void OnId_AgenteChanging(System.Nullable<int> value);
    partial void OnId_AgenteChanged();
    partial void OnId_SesionChanging(System.Nullable<int> value);
    partial void OnId_SesionChanged();
    partial void OnFuncion1Changing(string value);
    partial void OnFuncion1Changed();
    #endregion
		
		public Funcion()
		{
			this._Conductor = default(EntityRef<Conductor>);
			this._Tirador = default(EntityRef<Tirador>);
			this._Agente = default(EntityRef<Agente>);
			this._Sesion = default(EntityRef<Sesion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Funcion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Funcion
		{
			get
			{
				return this._Id_Funcion;
			}
			set
			{
				if ((this._Id_Funcion != value))
				{
					this.OnId_FuncionChanging(value);
					this.SendPropertyChanging();
					this._Id_Funcion = value;
					this.SendPropertyChanged("Id_Funcion");
					this.OnId_FuncionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Agente", DbType="Int")]
		public System.Nullable<int> Id_Agente
		{
			get
			{
				return this._Id_Agente;
			}
			set
			{
				if ((this._Id_Agente != value))
				{
					if (this._Agente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_AgenteChanging(value);
					this.SendPropertyChanging();
					this._Id_Agente = value;
					this.SendPropertyChanged("Id_Agente");
					this.OnId_AgenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Sesion", DbType="Int")]
		public System.Nullable<int> Id_Sesion
		{
			get
			{
				return this._Id_Sesion;
			}
			set
			{
				if ((this._Id_Sesion != value))
				{
					if (this._Sesion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_SesionChanging(value);
					this.SendPropertyChanging();
					this._Id_Sesion = value;
					this.SendPropertyChanged("Id_Sesion");
					this.OnId_SesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Funcion", Storage="_Funcion1", DbType="VarChar(30)")]
		public string Funcion1
		{
			get
			{
				return this._Funcion1;
			}
			set
			{
				if ((this._Funcion1 != value))
				{
					this.OnFuncion1Changing(value);
					this.SendPropertyChanging();
					this._Funcion1 = value;
					this.SendPropertyChanged("Funcion1");
					this.OnFuncion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Funcion_Conductor", Storage="_Conductor", ThisKey="Id_Funcion", OtherKey="Id_Funcion", IsUnique=true, IsForeignKey=false)]
		public Conductor Conductor
		{
			get
			{
				return this._Conductor.Entity;
			}
			set
			{
				Conductor previousValue = this._Conductor.Entity;
				if (((previousValue != value) 
							|| (this._Conductor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Conductor.Entity = null;
						previousValue.Funcion = null;
					}
					this._Conductor.Entity = value;
					if ((value != null))
					{
						value.Funcion = this;
					}
					this.SendPropertyChanged("Conductor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Funcion_Tirador", Storage="_Tirador", ThisKey="Id_Funcion", OtherKey="Id_Funcion", IsUnique=true, IsForeignKey=false)]
		public Tirador Tirador
		{
			get
			{
				return this._Tirador.Entity;
			}
			set
			{
				Tirador previousValue = this._Tirador.Entity;
				if (((previousValue != value) 
							|| (this._Tirador.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tirador.Entity = null;
						previousValue.Funcion = null;
					}
					this._Tirador.Entity = value;
					if ((value != null))
					{
						value.Funcion = this;
					}
					this.SendPropertyChanged("Tirador");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Agente_Funcion", Storage="_Agente", ThisKey="Id_Agente", OtherKey="Id_Agente", IsForeignKey=true)]
		public Agente Agente
		{
			get
			{
				return this._Agente.Entity;
			}
			set
			{
				Agente previousValue = this._Agente.Entity;
				if (((previousValue != value) 
							|| (this._Agente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Agente.Entity = null;
						previousValue.Funcion.Remove(this);
					}
					this._Agente.Entity = value;
					if ((value != null))
					{
						value.Funcion.Add(this);
						this._Id_Agente = value.Id_Agente;
					}
					else
					{
						this._Id_Agente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Agente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sesion_Funcion", Storage="_Sesion", ThisKey="Id_Sesion", OtherKey="Id_Sesion", IsForeignKey=true)]
		public Sesion Sesion
		{
			get
			{
				return this._Sesion.Entity;
			}
			set
			{
				Sesion previousValue = this._Sesion.Entity;
				if (((previousValue != value) 
							|| (this._Sesion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sesion.Entity = null;
						previousValue.Funcion.Remove(this);
					}
					this._Sesion.Entity = value;
					if ((value != null))
					{
						value.Funcion.Add(this);
						this._Id_Sesion = value.Id_Sesion;
					}
					else
					{
						this._Id_Sesion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Sesion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entorno")]
	public partial class Entorno
	{
		
		private string _Nombre;
		
		private string _Escenario;
		
		private string _Descripcion;
		
		private string _JsonOdin;
		
		public Entorno()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Escenario", DbType="VarChar(MAX)")]
		public string Escenario
		{
			get
			{
				return this._Escenario;
			}
			set
			{
				if ((this._Escenario != value))
				{
					this._Escenario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JsonOdin", DbType="VarChar(MAX)")]
		public string JsonOdin
		{
			get
			{
				return this._JsonOdin;
			}
			set
			{
				if ((this._JsonOdin != value))
				{
					this._JsonOdin = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Encargado")]
	public partial class Encargado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Encargado;
		
		private string _Usuario;
		
		private string _Pass;
		
		private System.Nullable<int> _Id_Agente;
		
		private EntitySet<Sesion> _Sesion;
		
		private EntityRef<Agente> _Agente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_EncargadoChanging(int value);
    partial void OnId_EncargadoChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnId_AgenteChanging(System.Nullable<int> value);
    partial void OnId_AgenteChanged();
    #endregion
		
		public Encargado()
		{
			this._Sesion = new EntitySet<Sesion>(new Action<Sesion>(this.attach_Sesion), new Action<Sesion>(this.detach_Sesion));
			this._Agente = default(EntityRef<Agente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Encargado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Encargado
		{
			get
			{
				return this._Id_Encargado;
			}
			set
			{
				if ((this._Id_Encargado != value))
				{
					this.OnId_EncargadoChanging(value);
					this.SendPropertyChanging();
					this._Id_Encargado = value;
					this.SendPropertyChanged("Id_Encargado");
					this.OnId_EncargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(20)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(30)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Agente", DbType="Int")]
		public System.Nullable<int> Id_Agente
		{
			get
			{
				return this._Id_Agente;
			}
			set
			{
				if ((this._Id_Agente != value))
				{
					if (this._Agente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_AgenteChanging(value);
					this.SendPropertyChanging();
					this._Id_Agente = value;
					this.SendPropertyChanged("Id_Agente");
					this.OnId_AgenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Encargado_Sesion", Storage="_Sesion", ThisKey="Id_Encargado", OtherKey="Id_Encargado")]
		public EntitySet<Sesion> Sesion
		{
			get
			{
				return this._Sesion;
			}
			set
			{
				this._Sesion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Agente_Encargado", Storage="_Agente", ThisKey="Id_Agente", OtherKey="Id_Agente", IsForeignKey=true)]
		public Agente Agente
		{
			get
			{
				return this._Agente.Entity;
			}
			set
			{
				Agente previousValue = this._Agente.Entity;
				if (((previousValue != value) 
							|| (this._Agente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Agente.Entity = null;
						previousValue.Encargado.Remove(this);
					}
					this._Agente.Entity = value;
					if ((value != null))
					{
						value.Encargado.Add(this);
						this._Id_Agente = value.Id_Agente;
					}
					else
					{
						this._Id_Agente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Agente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sesion(Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Encargado = this;
		}
		
		private void detach_Sesion(Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Encargado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sesion")]
	public partial class Sesion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Sesion;
		
		private string _Actividad;
		
		private string _Entorno;
		
		private string _Fecha;
		
		private System.Nullable<int> _Id_Encargado;
		
		private EntitySet<Funcion> _Funcion;
		
		private EntityRef<Encargado> _Encargado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_SesionChanging(int value);
    partial void OnId_SesionChanged();
    partial void OnActividadChanging(string value);
    partial void OnActividadChanged();
    partial void OnEntornoChanging(string value);
    partial void OnEntornoChanged();
    partial void OnFechaChanging(string value);
    partial void OnFechaChanged();
    partial void OnId_EncargadoChanging(System.Nullable<int> value);
    partial void OnId_EncargadoChanged();
    #endregion
		
		public Sesion()
		{
			this._Funcion = new EntitySet<Funcion>(new Action<Funcion>(this.attach_Funcion), new Action<Funcion>(this.detach_Funcion));
			this._Encargado = default(EntityRef<Encargado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Sesion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Sesion
		{
			get
			{
				return this._Id_Sesion;
			}
			set
			{
				if ((this._Id_Sesion != value))
				{
					this.OnId_SesionChanging(value);
					this.SendPropertyChanging();
					this._Id_Sesion = value;
					this.SendPropertyChanged("Id_Sesion");
					this.OnId_SesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Actividad", DbType="VarChar(30)")]
		public string Actividad
		{
			get
			{
				return this._Actividad;
			}
			set
			{
				if ((this._Actividad != value))
				{
					this.OnActividadChanging(value);
					this.SendPropertyChanging();
					this._Actividad = value;
					this.SendPropertyChanged("Actividad");
					this.OnActividadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entorno", DbType="VarChar(MAX)")]
		public string Entorno
		{
			get
			{
				return this._Entorno;
			}
			set
			{
				if ((this._Entorno != value))
				{
					this.OnEntornoChanging(value);
					this.SendPropertyChanging();
					this._Entorno = value;
					this.SendPropertyChanged("Entorno");
					this.OnEntornoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="VarChar(MAX)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Encargado", DbType="Int")]
		public System.Nullable<int> Id_Encargado
		{
			get
			{
				return this._Id_Encargado;
			}
			set
			{
				if ((this._Id_Encargado != value))
				{
					if (this._Encargado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_EncargadoChanging(value);
					this.SendPropertyChanging();
					this._Id_Encargado = value;
					this.SendPropertyChanged("Id_Encargado");
					this.OnId_EncargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sesion_Funcion", Storage="_Funcion", ThisKey="Id_Sesion", OtherKey="Id_Sesion")]
		public EntitySet<Funcion> Funcion
		{
			get
			{
				return this._Funcion;
			}
			set
			{
				this._Funcion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Encargado_Sesion", Storage="_Encargado", ThisKey="Id_Encargado", OtherKey="Id_Encargado", IsForeignKey=true)]
		public Encargado Encargado
		{
			get
			{
				return this._Encargado.Entity;
			}
			set
			{
				Encargado previousValue = this._Encargado.Entity;
				if (((previousValue != value) 
							|| (this._Encargado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Encargado.Entity = null;
						previousValue.Sesion.Remove(this);
					}
					this._Encargado.Entity = value;
					if ((value != null))
					{
						value.Sesion.Add(this);
						this._Id_Encargado = value.Id_Encargado;
					}
					else
					{
						this._Id_Encargado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Encargado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Funcion(Funcion entity)
		{
			this.SendPropertyChanging();
			entity.Sesion = this;
		}
		
		private void detach_Funcion(Funcion entity)
		{
			this.SendPropertyChanging();
			entity.Sesion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tirador")]
	public partial class Tirador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Funcion;
		
		private System.Nullable<bool> _Uso_Correcto;
		
		private System.Nullable<bool> _Mision_Cumplida;
		
		private System.Nullable<int> _Disparos_Realizados;
		
		private System.Nullable<int> _Disparos_Acertados;
		
		private System.Nullable<int> _Disparos_Colateral;
		
		private System.Nullable<int> _Bajas_Militares;
		
		private System.Nullable<int> _Bajas_Colaterales;
		
		private System.Nullable<int> _Bajas_Enemigos;
		
		private System.Nullable<double> _Tiempo;
		
		private EntityRef<Funcion> _Funcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_FuncionChanging(int value);
    partial void OnId_FuncionChanged();
    partial void OnUso_CorrectoChanging(System.Nullable<bool> value);
    partial void OnUso_CorrectoChanged();
    partial void OnMision_CumplidaChanging(System.Nullable<bool> value);
    partial void OnMision_CumplidaChanged();
    partial void OnDisparos_RealizadosChanging(System.Nullable<int> value);
    partial void OnDisparos_RealizadosChanged();
    partial void OnDisparos_AcertadosChanging(System.Nullable<int> value);
    partial void OnDisparos_AcertadosChanged();
    partial void OnDisparos_ColateralChanging(System.Nullable<int> value);
    partial void OnDisparos_ColateralChanged();
    partial void OnBajas_MilitaresChanging(System.Nullable<int> value);
    partial void OnBajas_MilitaresChanged();
    partial void OnBajas_ColateralesChanging(System.Nullable<int> value);
    partial void OnBajas_ColateralesChanged();
    partial void OnBajas_EnemigosChanging(System.Nullable<int> value);
    partial void OnBajas_EnemigosChanged();
    partial void OnTiempoChanging(System.Nullable<double> value);
    partial void OnTiempoChanged();
    #endregion
		
		public Tirador()
		{
			this._Funcion = default(EntityRef<Funcion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Funcion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Funcion
		{
			get
			{
				return this._Id_Funcion;
			}
			set
			{
				if ((this._Id_Funcion != value))
				{
					if (this._Funcion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_FuncionChanging(value);
					this.SendPropertyChanging();
					this._Id_Funcion = value;
					this.SendPropertyChanged("Id_Funcion");
					this.OnId_FuncionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uso_Correcto", DbType="Bit")]
		public System.Nullable<bool> Uso_Correcto
		{
			get
			{
				return this._Uso_Correcto;
			}
			set
			{
				if ((this._Uso_Correcto != value))
				{
					this.OnUso_CorrectoChanging(value);
					this.SendPropertyChanging();
					this._Uso_Correcto = value;
					this.SendPropertyChanged("Uso_Correcto");
					this.OnUso_CorrectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mision_Cumplida", DbType="Bit")]
		public System.Nullable<bool> Mision_Cumplida
		{
			get
			{
				return this._Mision_Cumplida;
			}
			set
			{
				if ((this._Mision_Cumplida != value))
				{
					this.OnMision_CumplidaChanging(value);
					this.SendPropertyChanging();
					this._Mision_Cumplida = value;
					this.SendPropertyChanged("Mision_Cumplida");
					this.OnMision_CumplidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disparos_Realizados", DbType="Int")]
		public System.Nullable<int> Disparos_Realizados
		{
			get
			{
				return this._Disparos_Realizados;
			}
			set
			{
				if ((this._Disparos_Realizados != value))
				{
					this.OnDisparos_RealizadosChanging(value);
					this.SendPropertyChanging();
					this._Disparos_Realizados = value;
					this.SendPropertyChanged("Disparos_Realizados");
					this.OnDisparos_RealizadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disparos_Acertados", DbType="Int")]
		public System.Nullable<int> Disparos_Acertados
		{
			get
			{
				return this._Disparos_Acertados;
			}
			set
			{
				if ((this._Disparos_Acertados != value))
				{
					this.OnDisparos_AcertadosChanging(value);
					this.SendPropertyChanging();
					this._Disparos_Acertados = value;
					this.SendPropertyChanged("Disparos_Acertados");
					this.OnDisparos_AcertadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disparos_Colateral", DbType="Int")]
		public System.Nullable<int> Disparos_Colateral
		{
			get
			{
				return this._Disparos_Colateral;
			}
			set
			{
				if ((this._Disparos_Colateral != value))
				{
					this.OnDisparos_ColateralChanging(value);
					this.SendPropertyChanging();
					this._Disparos_Colateral = value;
					this.SendPropertyChanged("Disparos_Colateral");
					this.OnDisparos_ColateralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bajas_Militares", DbType="Int")]
		public System.Nullable<int> Bajas_Militares
		{
			get
			{
				return this._Bajas_Militares;
			}
			set
			{
				if ((this._Bajas_Militares != value))
				{
					this.OnBajas_MilitaresChanging(value);
					this.SendPropertyChanging();
					this._Bajas_Militares = value;
					this.SendPropertyChanged("Bajas_Militares");
					this.OnBajas_MilitaresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bajas_Colaterales", DbType="Int")]
		public System.Nullable<int> Bajas_Colaterales
		{
			get
			{
				return this._Bajas_Colaterales;
			}
			set
			{
				if ((this._Bajas_Colaterales != value))
				{
					this.OnBajas_ColateralesChanging(value);
					this.SendPropertyChanging();
					this._Bajas_Colaterales = value;
					this.SendPropertyChanged("Bajas_Colaterales");
					this.OnBajas_ColateralesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bajas_Enemigos", DbType="Int")]
		public System.Nullable<int> Bajas_Enemigos
		{
			get
			{
				return this._Bajas_Enemigos;
			}
			set
			{
				if ((this._Bajas_Enemigos != value))
				{
					this.OnBajas_EnemigosChanging(value);
					this.SendPropertyChanging();
					this._Bajas_Enemigos = value;
					this.SendPropertyChanged("Bajas_Enemigos");
					this.OnBajas_EnemigosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tiempo", DbType="Float")]
		public System.Nullable<double> Tiempo
		{
			get
			{
				return this._Tiempo;
			}
			set
			{
				if ((this._Tiempo != value))
				{
					this.OnTiempoChanging(value);
					this.SendPropertyChanging();
					this._Tiempo = value;
					this.SendPropertyChanged("Tiempo");
					this.OnTiempoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Funcion_Tirador", Storage="_Funcion", ThisKey="Id_Funcion", OtherKey="Id_Funcion", IsForeignKey=true)]
		public Funcion Funcion
		{
			get
			{
				return this._Funcion.Entity;
			}
			set
			{
				Funcion previousValue = this._Funcion.Entity;
				if (((previousValue != value) 
							|| (this._Funcion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Funcion.Entity = null;
						previousValue.Tirador = null;
					}
					this._Funcion.Entity = value;
					if ((value != null))
					{
						value.Tirador = this;
						this._Id_Funcion = value.Id_Funcion;
					}
					else
					{
						this._Id_Funcion = default(int);
					}
					this.SendPropertyChanged("Funcion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
